server:
  port: 8080
spring:
  freemarker:
    suffix: .html
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  file-storage:
    default-platform: minio
    thumbnail-suffix: ".min.jpg"
    local:
      - platform: local # 存储平台标识
        enable-storage: true #是否开启本存储（只能选一种）
        enable-access: true #启用访问（线上请使用 Nginx 配置，效率更高）
        domain: "http://127.0.0.1:2222/" #访问域名，注意后面要和path-patterns保持一致，“/”结尾
        base-path: D:/pictures/test # 存储地址
        path-patterns: /** #访问路径
    minio:
      - platform: minio
        enable-storage: true  # 启用存储
        access-key: ak
        secret-key: sk
        end-point: http://ip:9000
        bucket-name: test
        domain: "http://ip:9000/test/" # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        base-path:  # 基础路径
upload:
  file:
    path: D:/pictures/test
    path.temp: H:/upload/test/temp